spring:
  profiles:
    active: local
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # 명백하게 명시만 해두면 안전하지만, 없어도 기본값이 SpringPhysicalNamingStrategy
        spring.jpa.hibernate.naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        jdbc:
          time-zone: Asia/Seoul

logging:
  level:
    p6spy: DEBUG
    com.p6spy.engine.spy: DEBUG

decorator:
  datasource:
    p6spy:
      enable-logging: true